/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment; 
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class Scheduler_ManageHalls extends javax.swing.JFrame {
    private HallScheduler hallScheduler;
    private ManageReservation manageReservation;

    public Scheduler_ManageHalls() {
        initComponents();
        hallScheduler = new HallScheduler("Halls_Info.txt");
        manageReservation = new ManageReservation("Hall_reservations.txt");
        loadReservationIds();
        setupActionListeners();
    }

    private void setupActionListeners() {
        cboResId.addActionListener(evt -> cboResIdActionPerformed(evt));
        btnBackHP.addActionListener(evt -> btnBackHPActionPerformed(evt));
        btnReset.addActionListener(evt -> btnResetActionPerformed(evt));
    }
            // loading the reservation Id
    private void loadReservationIds() {
        List<String> reservationIds = manageReservation.loadReservationIds();
        reservationIds.forEach(cboResId::addItem);
    }
            //Error handling method
    private void showError(String message) {
        javax.swing.JOptionPane.showMessageDialog(this, message, "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnBackHP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cboResId = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnDel = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHallManage = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));

        btnBackHP.setBackground(new java.awt.Color(0, 102, 204));
        btnBackHP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/back-24.png"))); // NOI18N
        btnBackHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackHPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Halls");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBackHP)
                .addGap(279, 279, 279)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackHP))
                .addContainerGap())
        );

        cboResId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboResIdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Reservation ID");

        btnDel.setBackground(new java.awt.Color(0, 102, 204));
        btnDel.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("Delete");
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(0, 102, 204));
        btnView.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblHallManage.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblHallManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall ID", "Hall Type", "Reservation Starts ", "Reservation Ends "
            }
        ));
        jScrollPane1.setViewportView(tblHallManage);

        btnEdit.setBackground(new java.awt.Color(0, 102, 204));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 102, 204));
        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnFilter.setBackground(new java.awt.Color(0, 102, 204));
        btnFilter.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(255, 255, 255));
        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cboResId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView)
                    .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addGap(39, 39, 39)
                .addComponent(btnDel)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboResId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackHPActionPerformed
        Scheduler_HomePage homePage = new Scheduler_HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackHPActionPerformed

    private void cboResIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboResIdActionPerformed
        System.out.println("Selected reservation ID: " 
                + cboResId.getSelectedItem());
    }//GEN-LAST:event_cboResIdActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
            String selectedId = (String) cboResId.getSelectedItem();
        if (selectedId == null || selectedId.isEmpty()) {
            showError("Please select a Reservation ID.");
            return;
        }
        loadReservationData(selectedId);
    }//GEN-LAST:event_btnViewActionPerformed

        private void loadReservationData(String selectedId) {
        DefaultTableModel model = (DefaultTableModel) tblHallManage.getModel();
        model.setRowCount(0);
        List<Reservation> reservations = manageReservation.getReservationsById(selectedId);
        reservations.forEach(reservation -> model.addRow(new Object[]{
                reservation.getHallID(),
                reservation.getHallType(),
                reservation.getStartTime(),
                reservation.getEndTime()
        }));
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
           String selectedReservationId = cboResId.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) tblHallManage.getModel();
        int selectedRow = tblHallManage.getSelectedRow();
        if (selectedRow == -1) {
            showError("Please select a row to edit.");
            return;
        }
        Reservation updatedReservation = new Reservation(
                model.getValueAt(selectedRow, 0).toString(),
                model.getValueAt(selectedRow, 1).toString(),
                model.getValueAt(selectedRow, 2).toString(),
                model.getValueAt(selectedRow, 3).toString(),
                selectedReservationId
        );
        manageReservation.updateReservation(updatedReservation);
        JOptionPane.showMessageDialog(null, "Changes saved successfully!");
        btnViewActionPerformed(null);
    }//GEN-LAST:event_btnEditActionPerformed
    
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
    // Retrieve the selected reservation ID from the combo box
    Object selectedItem = cboResId.getSelectedItem();
    
    // Check if a reservation ID is selected
    if (selectedItem == null) {        
        showError("Please select a reservation ID to delete.");
        return;    
    }
    
    String reservationId = selectedItem.toString(); // Safely convert to string now

    // Call the delete method
    manageReservation.deleteReservation(reservationId);
    JOptionPane.showMessageDialog(null, "The selected reservation " + reservationId + " has been deleted successfully.");
    
    // Reload the reservation IDs in the combo box
    loadReservationIds();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        String filterType = JOptionPane.showInputDialog(this, "Enter hall type to filter (or leave blank for all):");
        int minCapacity = getMinCapacity();
        if (minCapacity < 0) return;
        List<Halls> filteredHalls = hallScheduler.filterHalls(filterType, minCapacity);
        updateTableWithFilteredHalls(filteredHalls);
    }//GEN-LAST:event_btnFilterActionPerformed

    private int getMinCapacity() {
        try {
            String capacityInput = JOptionPane.showInputDialog(this, "Enter minimum capacity (or leave blank for no minimum):");
            return (capacityInput != null && !capacityInput.isEmpty()) ? Integer.parseInt(capacityInput) : 0;
        } catch (NumberFormatException e) {
            showError("Invalid capacity. Please enter a valid number.");
            return -1;
        }
    }

    private void updateTableWithFilteredHalls(List<Halls> halls) {
        DefaultTableModel model = (DefaultTableModel) tblHallManage.getModel();
        model.setRowCount(0);
        halls.forEach(hall -> model.addRow(new Object[]{
                hall.getHallID(),
                hall.getHallType(),
                hall.getCapacity(),
                hall.getBookingRate()
        }));
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cboResId.setSelectedIndex(-1); // Deselect any selected item
        loadReservationIds(); 
        loadAllReservationData();
    }//GEN-LAST:event_btnResetActionPerformed
    private void loadAllReservationData() {
         
        DefaultTableModel model = (DefaultTableModel) tblHallManage.getModel();
        model.setRowCount(0); // Clear existing rows
        List<Reservation> allReservations = manageReservation.getAllReservations(); 
        allReservations.forEach(reservation -> model.addRow(new Object[]{
                reservation.getHallID(),
                reservation.getHallType(),
                reservation.getStartTime(),
                reservation.getEndTime()    
        }));
}   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scheduler_ManageHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scheduler_ManageHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scheduler_ManageHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scheduler_ManageHalls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scheduler_ManageHalls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackHP;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cboResId;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHallManage;
    // End of variables declaration//GEN-END:variables
}
